### ISSUE TITLE
\dist\styles\styles.07300592.css references Google's CDN

### ISSUE THREAD

**Issue by eliazu** [dreamfactorysoftware/df-admin-app#49]
Hello,
the file references
@import url(//fonts.googleapis.com/css?family=Lato:400,700,400italic)

this making the buttons of the admin app "blank" if the app is installed on a network unconnected to the internet.
please solve this as you solved this:
https://github.com/dreamfactorysoftware/dsp-core/issues/32

thank you

**Comment by eliazu** [comment]
sorry ,
the fix is to add a reference to the font-awsome css file in the index.html file.

**Comment by drewpearce** [comment]
I'm not seeing this in the latest version. Can you confirm?

**Comment by drewpearce** [comment]
closing after no response
