### ISSUE TITLE
Logout 403 Forbidden

### ISSUE THREAD

**Issue by meiti** [dreamfactorysoftware/df-admin-app#64]
In the last version of df-admin-app, when I logout I get the following error:

"NetworkError: 403 Forbidden - http://df-test.local/api/v2/system/admin/session"

**Comment by drewpearce** [comment]
DF: 2.1.0 and Admin: 2.1.0?
Can you provide more information. I can't duplicate the error.

**Comment by meiti** [comment]
Excuse me, It was my mistake. It is closed.
